# Generated by Django 3.0.6 on 2020-06-01 18:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='UserData',
            fields=[
                ('id', models.CharField(db_column='_id', max_length=36, primary_key=True, serialize=False)),
                ('created_on', models.DateTimeField(auto_now_add=True)),
                ('updated_on', models.DateTimeField(auto_now=True)),
                ('email', models.EmailField(db_index=True, max_length=36, unique=True)),
                ('username', models.CharField(db_index=True, max_length=256, unique=True)),
                ('avatar_url', models.CharField(max_length=36)),
                ('short_name', models.CharField(max_length=256)),
                ('full_name', models.CharField(max_length=256)),
                ('birth_date', models.DateField()),
            ],
            options={
                'db_table': 'user_data',
                'db': 'mongo',
            },
        ),
    ]
